### ISSUE TITLE
Trouble with some player

### ISSUE THREAD

**Issue by shuchangbruce** [hlyford/nba-headshot-api#2]
Hi, I find your work very very handy actually. But some players are now showing up:
https://nba-players.herokuapp.com/players/james/lebron, can't find LeBron James
https://nba-players.herokuapp.com/players/james, you are showing James Young
https://nba-players.herokuapp.com/players/young/McCollum/cj, can't find C.J. McCollum

**Comment by tintinrus** [comment]
The problem is when a player has a capital letter somewhere in their name besides the first letter. (LeBron, McCollum, DeAndre)

**Comment by hlyford** [comment]
Hey guys, sorry for the delay. @shuchangbruce I haven't maintained this too well. Should be straightforward to normalize the name capitalization. If I have a chance I'll do it, or feel free to correct it and send in a PR.
